CREATE TABLE senior_projects (
    project_id              INTEGER primary key autoincrement,
    priority                int,
    title                   text unique,
    organization            text,
    primary_contact         text,
    contact_email           text,
    contact_phone           text,
    background_info         text,
    project_description     text,
    project_scope           text,
    project_challenges      text,
    constraints_assumptions text,
    sponsor_provided_resources  text,
    project_search_keywords text,
    dept_required_deliverables text,
    sponsor_deliverables    text,
    proprietary_info        text,
    sponsor_avail_checked   int,
    project_agreements_checked  int,
    assignment_of_rights    text,
    team_name               text,
    members                 text,
    sponsor                 text,
    coach                   text,
    poster                  text,
    video                   text,
    website                 text,
    synopsis                text
);