CREATE TABLE projects (
    project_id
    submission_datetime     DATETIME DEFAULT CURRENT_TIMESTAMP,
    status                  text,   -- Submitted, Needs Revision, Future Project, Candidate, In Progress, Completed, Archived (not related to archive table)
    display_name            text,
    title                   text,
    organization            text,
    primary_contact         text,
    contact_email           text,
    contact_phone           text,
    attachments             text,
    background_info         text,
    project_description     text,
    project_scope           text,
    project_challenges      text,
    constraints_assumptions text,
    sponsor_provided_resources  text,
    project_search_keywords text,
    sponsor_deliverables    text,
    proprietary_info        text,
    sponsor_avail_checked   int,
    sponsor_alternate_time  text,
    project_agreements_checked  int,
    assignment_of_rights    text,
    team_name               text,
    poster                  text,
    video                   text,
    website                 text,
    synopsis                text,
    sponsor                 integer,
    semester                integer,
    FOREIGN KEY (semester) REFERENCES semester_group(semester_id),
    FOREIGN KEY (sponsor) REFERENCES sponsors(sponsor_id)
);
